<?php

/**
 * @file
 * It has the functions to test the conection between the commerce site and
 * Punto Pago.
 */


/**
 * Amount of the order in the test.
 */
define('PUNTOPAGO_TEST_AMOUNT', 10000.55);


/**
 * Implements hook_permission().
 */
function puntopago_test_permission() {
  return array(
    'access to test puntopago' => array(
      'title' => t('Access to test puntopago'),
    ),
  );
}


/**
 * Implements hook_menu().
 */
function puntopago_test_menu() {
  $items = array();

  $items['puntopago-test'] = array(
    'title' => 'Punto Pago Test',
    'description' => 'Test a Punto Pago transaction',
    'page callback' => 'puntopago_test_page',
    'access arguments' => array('access to test puntopago'),
  );

  $items['puntopago-test/%'] = array(
    'title callback' => 'puntopago_test_title_callback',
    'title arguments' => array(1),
    'description' => 'Test a Punto Pago transaction for CLP',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('puntopago_test_form', 1),
    'access arguments' => array(1),
    'access callback' => 'puntopago_test_access_callback',
  );

  return $items;
}


/**
 * Access callback for the request puntopago-test/%.
 * @see puntopago_test_menu()
 *
 * @param string $currency
 *   Currency code: USD or CLP
 *
 * @return bool
 *   TRUE if the user has access and the currency is available. FALSE otherwise.
 */
function puntopago_test_access_callback($currency) {
  if (!user_access('access to test puntopago')) {
    return FALSE;
  }
  return puntopago_validate_currency($currency);
}


/**
 * Title callback for the request puntopago-test/%.
 * @see puntopago_test_menu()
 *
 * @param string $currency
 *   Currency code: USD or CLP.
 *
 * @return string
 *   Returns page title.
 */
function puntopago_test_title_callback($currency) {
  return t('Punto Pago Test !currency', array('!currency' => $currency));
}


/**
 * Builds the page to test Punto Pago.
 *
 * @return string
 *   themed test page.
 */
function puntopago_test_page() {
  $puntopago_settings = puntopago_get_settings_kcc();
  foreach ($puntopago_settings as $currency => $setting) {
    $item = t('Test on !currency', array('!currency' => $currency));
    if ($setting['puntopago_ROOT_CGI'] == '') {
      $items[] = $item . ' ' . t('Disabled');
    }
    else {
      $items[] = l($item, 'puntopago-test/' . $currency);
    }
  }

  return theme('item_list', array('items' => $items));
}


/**
 * Form information to test Punto Pago.
 *
 * @param mixed $form
 *   form element
 * @param mixed $form_state
 *   current form state
 * @param string $currency
 *   currency code.
 *
 * @return array
 *   form element
 */
function puntopago_test_form($form, $form_state, $currency) {
  global $base_url;

  $amount = PUNTOPAGO_TEST_AMOUNT;
  $order_number = 1;
  $session = 1;
  $commerce = 'puntopago_commerce_test';

  $params = puntopago_get_params(array(
    'amount'       => $amount,
    'currency'     => $currency,
    'order_number' => $order_number,
    'session'      => $session,
    'commerce'     => $commerce,
  ));

  $form = puntopago_redirect_form($form, $form_state, $params, t('Go to Punto Pago'), $currency);
  $args = array(
    '!amount' => puntopago_amount(PUNTOPAGO_TEST_AMOUNT, $currency, TRUE),
    '!currency' => $currency,
  );

  $help = t('With this form you can test the conection between your server and Punto Pago. The amount is !currency$ !amount and the order_id will be always 1.', $args);
  $help .= t('You will see a list with the parameters required by Punto Pago');

  $form['information'] = array(
    '#markup' => $help,
  );

  $rows = array();
  $rows[] = array(t('Currency'), $currency);
  foreach ($params as $name => $value) {
    $rows[] = array($name, $value);
  }

  $form['params'] = array(
    '#theme' => 'table',
    '#rows' => $rows,
    '#header' => array(t('Parameter'), t('Value')),
  );

  $form['submit']['#weight'] = 30;

  /*
   * We call the function with the currency to test the request to Punto Pago with
   * AJAX.
   */
  puntopago_redirect_js($currency);
  $form['submit_ajax'] = array(
    '#weight' => 31,
    '#type' => 'submit',
    '#value' => t('Go to Punto Pago with Ajax'),
    '#ajax' => array(
      'callback' => 'puntopago_test_ajax_submit',
    ),
  );

  return $form;
}


/**
 * Ajax Callback.
 *
 * Invokes puntopagoRedirect sending form values as parameters.
 *
 * @param array $form
 *   form element
 * @param array $form_state
 *   current form state
 *
 * @return array
 *   ajax command
 */
function puntopago_test_ajax_submit($form, $form_state) {

  $vals = array($form_state['values']);
  /* waiting message */
  $msg = t('Redirecting to Punto Pago, Please wait...');
  $html = '<div class="messages status">' . $msg . '</div>';
  $commands[] = ajax_command_prepend('#puntopago-test-form', $html);
  $commands[] = ajax_command_invoke(NULL, 'puntopagoRedirect', $vals);

  return array('#type' => 'ajax', '#commands' => $commands);
}


/**
 * Implements hook_puntopago_commerce_system().
 */
function puntopago_test_puntopago_commerce_system() {
  $info = array();
  $params = array('!url' => url('puntopago-test'));
  $t = t('You can test your conection with Punto Pago <a href="!url">here</a>', $params);
  $info['puntopago_commerce_test'] = array(
    'title'              => 'Punto Pago Test',
    'description'        => $t,
    'success'            => 'puntopago_test_success_default',
    'failure'            => 'puntopago_test_failure_default',
    'close validate'     => 'puntopago_test_validate_close_default',
    'order load'         => 'puntopago_test_order_load_default',
    'accept transaction' => 'puntopago_test_accept_transaction',
    'save transaction'   => 'puntopago_test_save_transaction',
  );
  return $info;
}


/**
 * Callback for failure case.
 *
 * @param int $order_id
 *   order identifier
 * @param mixed $transaction
 *   Transaction object as Punto Pago response to commerce request.
 *
 * @return string
 *   themed failure page
 */
function puntopago_test_failure_default($order_id, $transaction) {
  $variables = array(
    'order_id'          => $order_id,
    'redirection'       => 'puntopago-test',
    'title_redirection' => t('Try again'),
  );

  return theme('puntopago_failure', $variables);
}


/**
 * Callback for success case.
 *
 * @param int $order_id
 *   order identifier
 *
 * @return string
 *   themed success page
 */
function puntopago_test_success_default($order_id) {
  global $user;

  $params = array('!order_number' => $order_id);
  $output = t('Payment successful for the order !order_number', $params);

  $wpay_trans = puntopago_get_transaction_by_order($order_id, 'puntopago_commerce_test');
  $voucher = puntopago_prepare_for_voucher(array(
    'order_id'           => $order_id,
    'puntopago_transaction' => $wpay_trans,
    'client_name'        => isset($user->name) ? $user->name : t('Anonymous'),
  ));

  $output .= theme('puntopago_voucher', $voucher);
  $output .= '<p>' . l(t('Test puntopago again'), 'puntopago-test') . '</p>';

  return $output;
}


/**
 * Callback from commerce info default for order load.
 *
 * The PUNTOPAGO_TEST_AMOUNT is loaded in the order as the order total.
 *
 * @param array $order
 *   Generic Punto Pago's order.
 */
function puntopago_test_order_load_default(&$order) {
  $order['order_total'] = PUNTOPAGO_TEST_AMOUNT;
}


/**
 * Callback from close validate.
 *
 * Validates the order if it was closed or it is still open.
 * On this test case, we always simulate an open order.
 *
 * @param array $order
 *   Generic Punto Pago's order.
 *
 * @return bool
 *   It is true in order to use
 */
function puntopago_test_validate_close_default($order) {
  return TRUE;
}


/**
 * Callback from accept transaction.
 *
 * This function will be executed right after all validations. It is useful
 * to execute tasks like send an email or change the order state.
 * Because this module test does not have any orders, it is not used.
 *
 * @param array $order
 *   Generic Punto Pago's order.
 */
function puntopago_test_accept_transaction($order) {

}


/**
 * Callback from save transaction.
 *
 * This function is executed before puntopago_test_accept_transaction() and before
 * Punto Pago module has saved the data sended by Transbank.
 * It can be used in similar ways than the previous. Just actions, because
 * this function does not change the transaction nor return some value.
 * puntopago_test_accept_transaction().
 *
 * @param array $transaction
 *   Transaction object as Punto Pago response to commerce request.
 */
function puntopago_test_save_transaction($transaction) {

}
